### ISSUE TITLE
Conda package on nion channel broken for python 3.10

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift-instrumentation-kit#144]
Try something like `conda create -n test_env -c nion python=3.10 nionswift-instrumentation`
This will install `nionswift-instrumentation=0.19.3` because the latest version (and possibly some in between) have `python<3.10` as a requirement, even though the packages are built for python 3.10.

The packages from `conda-forge` are fine, only the ones from channel `nion` are affected.

**Comment by cmeyer** [comment]
Fixed 609f3d6b0290ae236ec8bf43b33a76748a6b3e54
