### ISSUE TITLE
Scan acquisition recorder has an arbitrary 100 frame limit which is too small

### ISSUE THREAD

**Issue by ndellby** [nion-software/nionswift-instrumentation-kit#31]

**Comment by cmeyer** [comment]
The original reason for the limit of 100 was to naively limit memory usage.

The full solution to this problem needs to take the scan size and channels into account and/or write to disk during acquisition.

@ndellby As a temporary solution, what would be a reasonable limit to place on it for now?

**Comment by ndellby** [comment]
300

**Comment by cmeyer** [comment]
The main issue is that the way scan recording is currently implemented, it uses up a lot of dedicated memory. 300 1024x1024 images will take over 1GB. (1024x1024x300x4bytes = 1.17GB).
