### ISSUE TITLE
Session metadata not included in acquired data when using "Capture" button

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift-instrumentation-kit#41]
Using "snapshot" does copy the (global) session metadata over to the acquired data, but using "Capture" doesn't.

Happens with the simulator and real hardware.

**Comment by cmeyer** [comment]
Hmmm. I keep thinking that we should have a better version of Capture anyway. Thanks for reporting.

**Comment by cmeyer** [comment]
This seems to work ok. See `test_capturing_during_view_captures_session` and ce464dffef61ca5c04089b42893c0d5dc7a2c118
