### ISSUE TITLE
Allow cameras to provide additional metadata in SI/4D acqusition mode

### ISSUE THREAD

**Issue by Brow71189** [nion-software/nionswift-instrumentation-kit#61]
Right now we have an awkward inconsistency in our acquisition code:
When acquiring live data, cameras produce `data_elements` whose `"properties"` entry gets copied into the `"hardware_source"` key of the resulting data item's metadata (see https://github.com/nion-software/nionswift-instrumentation-kit/blob/ca12c7246caff4e281ff30d25a057b5c48f8836b/nion/instrumentation/camera_base.py#L540).
In SI/4D mode, metadata coming from the camera is ignored completely, because the `"hardware_source"` key gets overwritten by the acquisition function (https://github.com/nion-software/nionswift-instrumentation-kit/blob/ca12c7246caff4e281ff30d25a057b5c48f8836b/nion/instrumentation/scan_base.py#L782).
One could of course just use a different key on the camera side, but that would make the metadata tags inconsistent between the two modes, so I don't think this is a good solution.

See #60 for an attempt to fix this.

**Comment by cmeyer** [comment]
Looks like this is fixed. Closing.
