### ISSUE TITLE
Acquisition pipeline for sequence of spectra reverts to single-frame fallback

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionswift-instrumentation-kit#92]
This is because the 'wrap' function does not work on the 'FramedDataStream' that is used when acquiring spectra.

**Comment by bentps** [comment]
Just a comment on this: it seems to be that fallback to series of single-frame acquisition if something goes wrong with the sequence acquire is worse than visibly failing with an error message. From the user perspective, a series of single frame images that takes 1000 times as long as the expected sequence is as bad or worse than a failure (in that it can take a lot of time and then return something not wanted), so it often isn't helpful to silently do that behavior. Anyway, hopefully the sequence stuff just works in the future, but I'd non-urgently suggest not having this fallback available if it ever fails.
